version: '3.8'
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf  # Add this line
  
  influxdb:
    image: influxdb:2
    ports:
      - "8086:8086"

  telegraf:
    image: telegraf:latest
    depends_on:
      - mosquitto
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    env_file: .env
    
  ip-beacon:
    build:
      context: ./IpBeacon
      dockerfile: Dockerfile
    ports:
      - "8888:8888/udp"
    volumes:
      - ./IpBeacon/appsettings.json:/app/appsettings.json
    restart: unless-stopped
